language: java
jdk: oraclejdk8
script: "./gradlew clean build publishToRepo"
after_success:
- "./gradlew jacocoTestReport coveralls"
env:
  global:
    secure: ay/zl3nTNZFrzoWH3uP6QapQbVrtz1VsDGrgHB1GHLztu3Q8GO51yhG3zfP2PTroqT9ASRrc3FTtGcOZeOfGWkJeqb0tSk0Bq+u0FKKmn3QoNBXhu1MOqphbeG0Yewsp3hSLiQu2TysakRvJXlACSZzz0g09PXoYm+lz6enVDoY=
